/* Vehicle list for the instant estimate.
   Every model belongs to a body style. Each body style is priced at one of the package-card sizes
   (car / suv / truck) with a small adjustment for bigger or smaller vehicles.
   To add a model, drop its name into the right list for its make. Anything missing can choose "Other". */
window.WD_VEHICLES = {
  types: {
    compact: { label: 'Compact car', size: 'car', adjust: 0 },
    coupe: { label: 'Coupe / sports car', size: 'car', adjust: 0 },
    sedan: { label: 'Sedan', size: 'car', adjust: 0.05 },
    'small-suv': { label: 'Small SUV / crossover', size: 'suv', adjust: 0 },
    'midsize-suv': { label: 'Midsize SUV', size: 'suv', adjust: 0.08 },
    'three-row': { label: '3-row SUV', size: 'truck', adjust: -0.05 },
    'large-suv': { label: 'Full-size SUV', size: 'truck', adjust: 0.1 },
    'midsize-truck': { label: 'Midsize pickup', size: 'truck', adjust: -0.08 },
    truck: { label: 'Full-size pickup', size: 'truck', adjust: 0 },
    'hd-truck': { label: 'Heavy-duty pickup', size: 'truck', adjust: 0.1 },
    minivan: { label: 'Minivan', size: 'truck', adjust: 0 },
    van: { label: 'Full-size van', size: 'truck', adjust: 0.15 },
  },

  makes: {
    Acura: {
      compact: ['ILX', 'Integra', 'RSX'],
      coupe: ['NSX'],
      sedan: ['RL', 'RLX', 'TL', 'TLX', 'TSX'],
      'small-suv': ['RDX'],
      'midsize-suv': ['ZDX'],
      'three-row': ['MDX'],
    },
    'Alfa Romeo': {
      sedan: ['Giulia'],
      'small-suv': ['Stelvio', 'Tonale'],
    },
    Audi: {
      compact: ['A3'],
      coupe: ['A5', 'R8', 'TT'],
      sedan: ['A4', 'A6', 'A7', 'A8', 'e-tron GT'],
      'small-suv': ['Q3', 'Q4 e-tron', 'Q5'],
      'midsize-suv': ['e-tron', 'Q8'],
      'three-row': ['Q7'],
    },
    BMW: {
      compact: ['i3'],
      coupe: ['2 Series', '4 Series', '8 Series', 'Z4'],
      sedan: ['3 Series', '5 Series', '7 Series', 'i4', 'i5', 'i7'],
      'small-suv': ['X1', 'X2', 'X3', 'X4'],
      'midsize-suv': ['iX', 'X5', 'X6'],
      'three-row': ['X7'],
    },
    Buick: {
      compact: ['Verano'],
      sedan: ['LaCrosse', 'Lucerne', 'Regal'],
      'small-suv': ['Encore', 'Encore GX', 'Envision', 'Envista'],
      'midsize-suv': ['Rendezvous'],
      'three-row': ['Enclave'],
    },
    Cadillac: {
      sedan: ['ATS', 'CT4', 'CT5', 'CT6', 'CTS', 'DTS', 'XTS'],
      'small-suv': ['XT4'],
      'midsize-suv': ['Lyriq', 'SRX', 'XT5'],
      'three-row': ['XT6'],
      'large-suv': ['Escalade', 'Escalade ESV'],
    },
    Chevrolet: {
      compact: ['Aveo', 'Bolt EV', 'Cobalt', 'Cruze', 'HHR', 'Sonic', 'Spark', 'Volt'],
      coupe: ['Camaro', 'Corvette'],
      sedan: ['Impala', 'Malibu'],
      'small-suv': ['Bolt EUV', 'Equinox', 'Trailblazer', 'Trax'],
      'midsize-suv': ['Blazer'],
      'three-row': ['Traverse'],
      'large-suv': ['Suburban', 'Tahoe'],
      'midsize-truck': ['Colorado', 'S-10'],
      truck: ['Avalanche', 'Silverado 1500'],
      'hd-truck': ['Silverado 2500HD', 'Silverado 3500HD'],
      minivan: ['Uplander'],
      van: ['Express'],
    },
    Chrysler: {
      compact: ['PT Cruiser'],
      sedan: ['200', '300', 'Sebring'],
      minivan: ['Pacifica', 'Town & Country', 'Voyager'],
    },
    Dodge: {
      compact: ['Caliber', 'Dart', 'Neon'],
      coupe: ['Challenger', 'Viper'],
      sedan: ['Avenger', 'Charger', 'Magnum'],
      'small-suv': ['Hornet'],
      'midsize-suv': ['Journey', 'Nitro'],
      'three-row': ['Durango'],
      'midsize-truck': ['Dakota'],
      minivan: ['Caravan', 'Grand Caravan'],
    },
    Fiat: {
      compact: ['500', '500L'],
      'small-suv': ['500X'],
    },
    Ford: {
      compact: ['Fiesta', 'Focus'],
      coupe: ['Mustang'],
      sedan: ['Crown Victoria', 'Five Hundred', 'Fusion', 'Taurus'],
      'small-suv': ['Bronco Sport', 'EcoSport', 'Escape', 'Mustang Mach-E'],
      'midsize-suv': ['Bronco', 'Edge'],
      'three-row': ['Explorer', 'Flex', 'Freestyle'],
      'large-suv': ['Excursion', 'Expedition', 'Expedition MAX'],
      'midsize-truck': ['Maverick', 'Ranger'],
      truck: ['F-150', 'F-150 Lightning'],
      'hd-truck': ['F-250 Super Duty', 'F-350 Super Duty'],
      minivan: ['Transit Connect'],
      van: ['E-Series', 'Transit'],
    },
    Genesis: {
      sedan: ['G70', 'G80', 'G90'],
      'small-suv': ['GV60', 'GV70'],
      'three-row': ['GV80'],
    },
    GMC: {
      'small-suv': ['Terrain'],
      'midsize-suv': ['Envoy'],
      'three-row': ['Acadia'],
      'large-suv': ['Yukon', 'Yukon XL'],
      'midsize-truck': ['Canyon'],
      truck: ['Hummer EV', 'Sierra 1500'],
      'hd-truck': ['Sierra 2500HD', 'Sierra 3500HD'],
      van: ['Savana'],
    },
    Honda: {
      compact: ['Civic', 'Fit', 'Insight'],
      coupe: ['CR-Z', 'S2000'],
      sedan: ['Accord', 'Clarity'],
      'small-suv': ['CR-V', 'Element', 'HR-V'],
      'midsize-suv': ['Passport', 'Prologue'],
      'three-row': ['Pilot'],
      'midsize-truck': ['Ridgeline'],
      minivan: ['Odyssey'],
    },
    Hummer: {
      'midsize-suv': ['H3'],
      'large-suv': ['H2'],
    },
    Hyundai: {
      compact: ['Accent', 'Elantra', 'Ioniq', 'Veloster'],
      sedan: ['Azera', 'Genesis', 'Ioniq 6', 'Sonata'],
      'small-suv': ['Ioniq 5', 'Kona', 'Tucson', 'Venue'],
      'midsize-suv': ['Santa Fe'],
      'three-row': ['Palisade', 'Veracruz'],
      'midsize-truck': ['Santa Cruz'],
    },
    Infiniti: {
      coupe: ['Q60'],
      sedan: ['G35', 'G37', 'M35', 'Q50', 'Q70'],
      'small-suv': ['QX30', 'QX50', 'QX55'],
      'midsize-suv': ['FX35', 'QX70'],
      'three-row': ['JX35', 'QX60'],
      'large-suv': ['QX56', 'QX80'],
    },
    Jaguar: {
      coupe: ['F-Type'],
      sedan: ['XE', 'XF', 'XJ'],
      'small-suv': ['E-Pace', 'I-Pace'],
      'midsize-suv': ['F-Pace'],
    },
    Jeep: {
      'small-suv': ['Cherokee', 'Compass', 'Liberty', 'Patriot', 'Renegade'],
      'midsize-suv': ['Grand Cherokee', 'Wrangler', 'Wrangler Unlimited'],
      'three-row': ['Commander', 'Grand Cherokee L'],
      'large-suv': ['Grand Wagoneer', 'Wagoneer'],
      'midsize-truck': ['Gladiator'],
    },
    Kia: {
      compact: ['Forte', 'Rio', 'Soul'],
      sedan: ['Cadenza', 'K5', 'Optima', 'Stinger'],
      'small-suv': ['EV6', 'Niro', 'Seltos', 'Sportage'],
      'midsize-suv': ['Sorento'],
      'three-row': ['EV9', 'Telluride'],
      minivan: ['Carnival', 'Sedona'],
    },
    'Land Rover': {
      'small-suv': ['Discovery Sport', 'Range Rover Evoque'],
      'midsize-suv': ['Defender', 'Range Rover Sport', 'Range Rover Velar'],
      'three-row': ['Discovery', 'LR4'],
      'large-suv': ['Range Rover'],
    },
    Lexus: {
      compact: ['CT'],
      coupe: ['LC', 'RC'],
      sedan: ['ES', 'GS', 'IS', 'LS'],
      'small-suv': ['NX', 'UX'],
      'midsize-suv': ['RX'],
      'three-row': ['GX', 'TX'],
      'large-suv': ['LX'],
    },
    Lincoln: {
      sedan: ['Continental', 'MKS', 'MKZ', 'Town Car'],
      'small-suv': ['Corsair', 'MKC'],
      'midsize-suv': ['MKX', 'Nautilus'],
      'three-row': ['Aviator', 'MKT'],
      'large-suv': ['Navigator'],
    },
    Mazda: {
      compact: ['Mazda2', 'Mazda3'],
      coupe: ['MX-5 Miata', 'RX-8'],
      sedan: ['Mazda6'],
      'small-suv': ['CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-7', 'MX-30', 'Tribute'],
      'midsize-suv': ['CX-70'],
      'three-row': ['CX-9', 'CX-90'],
      minivan: ['Mazda5'],
    },
    'Mercedes-Benz': {
      compact: ['A-Class', 'CLA'],
      sedan: ['C-Class', 'CLS', 'E-Class', 'EQE', 'EQS', 'S-Class'],
      'small-suv': ['GLA', 'GLB', 'GLC'],
      'midsize-suv': ['G-Class', 'GLE', 'M-Class'],
      'three-row': ['GL-Class', 'GLS'],
      minivan: ['Metris'],
      van: ['Sprinter'],
    },
    Mercury: {
      sedan: ['Grand Marquis', 'Milan', 'Sable'],
      'small-suv': ['Mariner'],
      'three-row': ['Mountaineer'],
    },
    Mini: {
      compact: ['Clubman', 'Cooper', 'Hardtop', 'Paceman'],
      'small-suv': ['Countryman'],
    },
    Mitsubishi: {
      compact: ['Lancer', 'Mirage'],
      coupe: ['Eclipse'],
      sedan: ['Galant'],
      'small-suv': ['Eclipse Cross', 'Outlander Sport'],
      'midsize-suv': ['Endeavor', 'Outlander'],
    },
    Nissan: {
      compact: ['Cube', 'Leaf', 'Sentra', 'Versa'],
      coupe: ['350Z', '370Z', 'GT-R', 'Z'],
      sedan: ['Altima', 'Maxima'],
      'small-suv': ['Ariya', 'Juke', 'Kicks', 'Rogue', 'Rogue Sport'],
      'midsize-suv': ['Murano', 'Xterra'],
      'three-row': ['Pathfinder'],
      'large-suv': ['Armada'],
      'midsize-truck': ['Frontier'],
      truck: ['Titan'],
      minivan: ['NV200', 'Quest'],
      van: ['NV Cargo', 'NV Passenger'],
    },
    Pontiac: {
      compact: ['G5', 'Vibe'],
      coupe: ['Solstice'],
      sedan: ['G6', 'G8', 'Grand Am', 'Grand Prix'],
      'small-suv': ['Torrent'],
      'midsize-suv': ['Aztek'],
      minivan: ['Montana'],
    },
    Porsche: {
      coupe: ['718 Boxster', '718 Cayman', '911'],
      sedan: ['Panamera', 'Taycan'],
      'small-suv': ['Macan'],
      'midsize-suv': ['Cayenne'],
    },
    Ram: {
      truck: ['1500'],
      'hd-truck': ['2500', '3500'],
      minivan: ['ProMaster City'],
      van: ['ProMaster'],
    },
    Rivian: {
      'three-row': ['R1S'],
      truck: ['R1T'],
    },
    Saturn: {
      compact: ['Ion'],
      coupe: ['Sky'],
      sedan: ['Aura'],
      'small-suv': ['Vue'],
      'three-row': ['Outlook'],
    },
    Scion: {
      compact: ['iA', 'iM', 'iQ', 'xA', 'xB', 'xD'],
      coupe: ['FR-S', 'tC'],
    },
    Subaru: {
      compact: ['Impreza', 'WRX'],
      coupe: ['BRZ'],
      sedan: ['Legacy'],
      'small-suv': ['Crosstrek', 'Forester', 'Outback', 'Solterra'],
      'three-row': ['Ascent', 'Tribeca'],
      'midsize-truck': ['Baja'],
    },
    Tesla: {
      sedan: ['Model 3', 'Model S'],
      'small-suv': ['Model Y'],
      'three-row': ['Model X'],
      truck: ['Cybertruck'],
    },
    Toyota: {
      compact: ['Corolla', 'Corolla iM', 'Matrix', 'Prius', 'Prius c', 'Yaris'],
      coupe: ['86', 'GR86', 'GR Supra', 'Solara'],
      sedan: ['Avalon', 'Camry', 'Crown', 'Mirai'],
      'small-suv': ['bZ4X', 'C-HR', 'Corolla Cross', 'RAV4', 'Venza'],
      'midsize-suv': ['4Runner', 'FJ Cruiser'],
      'three-row': ['Grand Highlander', 'Highlander'],
      'large-suv': ['Land Cruiser', 'Sequoia'],
      'midsize-truck': ['Tacoma'],
      truck: ['Tundra'],
      minivan: ['Sienna'],
    },
    Volkswagen: {
      compact: ['Beetle', 'Golf', 'GTI', 'Jetta'],
      coupe: ['Eos'],
      sedan: ['Arteon', 'CC', 'Passat'],
      'small-suv': ['ID.4', 'Taos', 'Tiguan'],
      'midsize-suv': ['Atlas Cross Sport', 'Touareg'],
      'three-row': ['Atlas'],
      minivan: ['ID. Buzz', 'Routan'],
    },
    Volvo: {
      sedan: ['S40', 'S60', 'S80', 'S90', 'V60', 'V90'],
      'small-suv': ['C40', 'EX30', 'XC40', 'XC60', 'XC70'],
      'three-row': ['EX90', 'XC90'],
    },
  },
};
